{% set name = "tyco" %}
{% set version = "0.3.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  git_url: https://github.com/typedconfig/tyco-python.git
  git_branch: main

build:
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv"

requirements:
  build:
    - python >=3.8
    - pip
    - setuptools >=61.0
    - wheel
  host:
    - python >=3.8
    - pip
    - setuptools >=61.0
    - wheel
  run:
    - python >=3.8

about:
  home: https://typedconfig.io
  summary: A Python library for the Typed Configuration language
  license: MIT
  license_file: LICENSE
  dev_url: https://github.com/typedconfig/tyco-python

extra:
  imports:
    - tyco
  commands:
    - tyco --help
  requires:
    - pytest
  dev_url: https://github.com/typedconfig/tyco-python

extra:
  recipe-maintainers:
    - mlauria
